### ISSUE TITLE
`autograder.zip` from `otter generate` fails to build autograder image on gradescope.com

### ISSUE THREAD

**Issue by tbrown122387** [ucbds-infra/otter-grader#944]
**Describe the bug**

`autograder.zip` created by `otter generate` doesn't built an autograder on gradescope.com

**To Reproduce**
Take any autograder test bundle, `cd` in there, then type `otter generate -t tests/`. Upload `autograder.zip` to gradescope.com programming assignment.

I apologize--I can't upload my real test files because it would be revealing private solution keys. 

**Expected behavior**
Uploading the `.zip` to gradescope shouldn't produce any build errors. 

**Versions**
from `otter --version`...
```
Python version: 3.13.5
Otter-Grader version: 6.1.4

Additional package versions:
    dill: 0.4.0
    fica: 0.4.1
    IPython: 9.4.0
    nbconvert: 7.16.6
    nbformat: 5.10.4
```

**Additional context**

Similar to [this bug](https://github.com/ucbds-infra/otter-grader/issues/892)

I tried the proposed fix mentioned [here](https://github.com/ucbds-infra/otter-grader/issues/892#issuecomment-2543463022). I also tried adding `libnspr4, libnss3, libgbm1` to the `apt get` command. Both get rid of the final error about playwright, but still the same final error remains: `The command '/bin/sh -c bash /gradescope/setup.sh' returned a non-zero code: 109`

[build_output.txt](https://github.com/user-attachments/files/22322043/build_output.txt)

**Comment by chrispyles** [comment]
Please PM me the old and new autograder.zip files on the Otter slack (link in README) and I will take a look.

**Comment by chrispyles** [comment]
@tbrown122387 I believe the issue you're having was fixed in v6.1.3. Please upgrade to that version or later and rerun `otter generate`.

**Comment by tbrown122387** [comment]
Sorry for the late response. It's only been an issue on one of my machines. I might've DM'd you an autograder zip from the machine it works fine on. 

As you can see above, I'm already > v6.1.3.  and even when I upgrade to the following, it still fails. I will DM you the verified broken one right now. 

```
Python version: 3.13.5
Otter-Grader version: 6.1.6

Additional package versions:
    dill: 0.4.0
    fica: 0.4.1
    IPython: 9.4.0
    nbconvert: 7.16.6
    nbformat: 5.10.4
```

**Comment by tbrown122387** [comment]
```
(base) taylor@taylor-Latitude-5420:~/stat-5430/autograding/Python/2.3$ conda list
# packages in environment at /home/taylor/miniconda3:
#
# Name                           Version          Build               Channel
_libgcc_mutex                    0.1              main
_openmp_mutex                    5.1              1_gnu
adwaita-icon-theme               48.0             h06a4308_0
alabaster                        1.0.0            pypi_0              pypi
anaconda-anon-usage              0.7.1            py313hfc0e8ea_100
annotated-types                  0.6.0            py313h06a4308_0
anyio                            4.10.0           pyhe01879c_0        conda-forge
archspec                         0.2.3            pyhd3eb1b0_0
argon2-cffi                      25.1.0           pyhd8ed1ab_0        conda-forge
argon2-cffi-bindings             21.2.0           py313h5eee18b_1
arrow                            1.3.0            pyhd8ed1ab_1        conda-forge
asttokens                        3.0.0            pyhd8ed1ab_1        conda-forge
async-lru                        2.0.5            pyh29332c3_0        conda-forge
at-spi2-atk                      2.34.2           hfac8509_1
at-spi2-core                     2.36.0           h597f2ad_2
atk-1.0                          2.36.0           ha1a6a79_0
attrs                            25.3.0           pyh71513ae_0        conda-forge
babel                            2.17.0           pyhd8ed1ab_0        conda-forge
beautifulsoup4                   4.13.4           pyha770c72_0        conda-forge
bleach                           6.2.0            pyh29332c3_4        conda-forge
bleach-with-css                  6.2.0            h82add2a_4          conda-forge
boltons                          25.0.0           py313h06a4308_0
boost-cpp                        1.82.0           hdb19cb5_2
brotlicffi                       1.0.9.2          py313h6a678d5_1
bzip2                            1.0.8            h5eee18b_6
c-ares                           1.19.1           h5eee18b_0
ca-certificates                  2025.8.3         hbd8a1cb_0          conda-forge
cached-property                  1.5.2            hd8ed1ab_1          conda-forge
cached_property                  1.5.2            pyha770c72_1        conda-forge
cairo                            1.16.0           he5ede1b_6
certifi                          2025.8.3         pyhd8ed1ab_0        conda-forge
cffi                             1.17.1           py313h1fdaa30_1
charset-normalizer               3.3.2            pyhd3eb1b0_0
click                            8.2.1            pypi_0              pypi
comm                             0.2.3            pyhe01879c_0        conda-forge
conda                            25.7.0           py313h78bf25f_0     conda-forge
conda-anaconda-telemetry         0.2.0            py313h06a4308_1
conda-anaconda-tos               0.2.1            py313h06a4308_0
conda-content-trust              0.2.0            py313h06a4308_1
conda-libmamba-solver            25.4.0           pyhd3eb1b0_0
conda-package-handling           2.4.0            py313h06a4308_0
conda-package-streaming          0.12.0           py313h06a4308_0
cpp-expected                     1.1.0            hdb19cb5_0
cryptography                     45.0.3           py313h2ccb017_0
dbus                             1.13.18          hb2f20db_0
debugpy                          1.8.11           py313h6a678d5_0
decorator                        5.2.1            pyhd8ed1ab_0        conda-forge
defusedxml                       0.7.1            pyhd8ed1ab_0        conda-forge
dill                             0.4.0            pypi_0              pypi
distro                           1.9.0            py313h06a4308_0
docutils                         0.21.2           pypi_0              pypi
epoxy                            1.5.4            h7f8727e_2
exceptiongroup                   1.3.0            pyhd8ed1ab_0        conda-forge
executing                        2.2.0            pyhd8ed1ab_0        conda-forge
expat                            2.7.1            h6a678d5_0
fica                             0.4.1            pypi_0              pypi
fmt                              9.1.0            hdb19cb5_1
font-ttf-dejavu-sans-mono        2.37             hd3eb1b0_0
font-ttf-inconsolata             2.001            hcb22688_0
font-ttf-source-code-pro         2.030            hd3eb1b0_0
font-ttf-ubuntu                  0.83             h8b1ccd4_0
fontconfig                       2.14.1           h55d465d_3
fonts-anaconda                   1                h8fa9717_0
fonts-conda-ecosystem            1                hd3eb1b0_0
fqdn                             1.5.1            pyhd8ed1ab_1        conda-forge
freetype                         2.13.3           h4a9f257_0
fribidi                          1.0.10           h7b6447c_0
frozendict                       2.4.2            py313h06a4308_0
gdk-pixbuf                       2.42.10          h64b468e_2
gettext                          0.21.0           hedfda30_2
giflib                           5.2.2            h5eee18b_0
glib                             2.84.2           h6a678d5_0
glib-tools                       2.84.2           h6a678d5_0
gobject-introspection            1.84.0           py313hcb37abf_0
graphite2                        1.3.14           h295c915_1
graphviz                         0.21             pypi_0              pypi
greenlet                         3.2.4            pypi_0              pypi
gtk3                             3.24.21          h40e4fd3_8
gts                              0.7.6            hb67d8dd_3
h11                              0.16.0           pyhd8ed1ab_0        conda-forge
h2                               4.2.0            pyhd8ed1ab_0        conda-forge
harfbuzz                         10.2.0           hdfddeaa_1
hicolor-icon-theme               0.17             h06a4308_2
hpack                            4.1.0            pyhd8ed1ab_0        conda-forge
httpcore                         1.0.9            pyh29332c3_0        conda-forge
httpx                            0.28.1           pyhd8ed1ab_0        conda-forge
hyperframe                       6.1.0            pyhd8ed1ab_0        conda-forge
icu                              73.1             h6a678d5_0
idna                             3.7              py313h06a4308_0
imagesize                        1.4.1            pypi_0              pypi
importlib-metadata               8.7.0            pyhe01879c_1        conda-forge
ipykernel                        6.30.1           pyh82676e8_0        conda-forge
ipylab                           1.1.0            pypi_0              pypi
ipython                          9.4.0            pyhfa0c392_0        conda-forge
ipython_pygments_lexers          1.1.1            pyhd8ed1ab_0        conda-forge
ipywidgets                       8.1.7            pypi_0              pypi
isoduration                      20.11.0          pyhd8ed1ab_1        conda-forge
jedi                             0.19.2           pyhd8ed1ab_1        conda-forge
jinja2                           3.1.6            pyhd8ed1ab_0        conda-forge
jpeg                             9e               h5eee18b_3
json5                            0.12.0           pyhd8ed1ab_0        conda-forge
jsonpatch                        1.33             py313h06a4308_1
jsonpointer                      2.1              pyhd3eb1b0_0
jsonschema                       4.25.0           pyhe01879c_0        conda-forge
jsonschema-specifications        2025.4.1         pyh29332c3_0        conda-forge
jsonschema-with-format-nongpl    4.25.0           he01879c_0          conda-forge
jupyter-lsp                      2.2.6            pyhe01879c_0        conda-forge
jupyter_client                   8.6.3            pyhd8ed1ab_1        conda-forge
jupyter_core                     5.8.1            pyh31011fe_0        conda-forge
jupyter_events                   0.12.0           pyh29332c3_0        conda-forge
jupyter_server                   2.16.0           pyhe01879c_0        conda-forge
jupyter_server_terminals         0.5.3            pyhd8ed1ab_1        conda-forge
jupyterlab                       4.4.5            pyhd8ed1ab_0        conda-forge
jupyterlab-widgets               3.0.15           pypi_0              pypi
jupyterlab_pygments              0.3.0            pyhd8ed1ab_2        conda-forge
jupyterlab_server                2.27.3           pyhd8ed1ab_1        conda-forge
jupytext                         1.17.2           pypi_0              pypi
krb5                             1.21.3           h8a1dbc1_1
lark                             1.2.2            pyhd8ed1ab_1        conda-forge
lcms2                            2.16             h92b89f2_1
ld_impl_linux-64                 2.40             h12ee557_0
lerc                             4.0.0            h6a678d5_0
libarchive                       3.7.7            hfab0078_0
libboost                         1.82.0           h109eef0_2
libcups                          2.4.2            h252cb56_2
libcurl                          8.14.1           h31d0fb7_0
libdeflate                       1.22             h5eee18b_0
libedit                          3.1.20230828     h5eee18b_0
libev                            4.33             h7f8727e_1
libffi                           3.4.4            h6a678d5_1
libgcc-ng                        11.2.0           h1234567_1
libgd                            2.3.3            h536bbd8_4
libglib                          2.84.2           h37c7471_0
libgomp                          11.2.0           h1234567_1
libiconv                         1.16             h5eee18b_3
libmamba                         2.0.5            haf1ee3a_1
libmambapy                       2.0.5            py313hdb19cb5_1
libmpdec                         4.0.0            h5eee18b_0
libnghttp2                       1.57.0           h2d74bed_0
libpng                           1.6.39           h5eee18b_0
librsvg                          2.56.3           hb0330b6_2
libsodium                        1.0.18           h36c2ea0_1          conda-forge
libsolv                          0.7.30           he621ea3_1
libssh2                          1.11.1           h251f7ec_0
libstdcxx-ng                     11.2.0           h1234567_1
libtiff                          4.7.0            hde9077f_0
libtool                          2.4.7            h6a678d5_0
libuuid                          1.41.5           h5eee18b_0
libwebp                          1.3.2            h9f374a3_1
libwebp-base                     1.3.2            h5eee18b_1
libxcb                           1.17.0           h9b100fa_0
libxml2                          2.13.8           hfdd30dd_0
lz4-c                            1.9.4            h6a678d5_1
markdown-it-py                   2.2.0            py313h06a4308_1
markupsafe                       3.0.2            pyhe1237c8_1        conda-forge
matplotlib-inline                0.1.7            pyhd8ed1ab_1        conda-forge
mdit-py-plugins                  0.5.0            pypi_0              pypi
mdurl                            0.1.0            py313h06a4308_0
menuinst                         2.3.0            py313h06a4308_0
mistune                          3.1.3            pyh29332c3_0        conda-forge
nbclient                         0.10.2           pyhd8ed1ab_0        conda-forge
nbconvert-core                   7.16.6           pyh29332c3_0        conda-forge
nbformat                         5.10.4           pyhd8ed1ab_1        conda-forge
ncurses                          6.4              h6a678d5_0
nest-asyncio                     1.6.0            pyhd8ed1ab_1        conda-forge
ninja                            1.12.1           h06a4308_0
ninja-base                       1.12.1           hdb19cb5_0
nlohmann_json                    3.11.2           h6a678d5_0
notebook-shim                    0.2.4            pyhd8ed1ab_1        conda-forge
nspr                             4.35             h6a678d5_0
nss                              3.89.1           h6a678d5_0
numpy                            2.3.2            pypi_0              pypi
openjpeg                         2.5.2            h0d4d230_1
openssl                          3.0.17           h5eee18b_0
otter-grader                     6.1.6            pypi_0              pypi
overrides                        7.7.0            pyhd8ed1ab_1        conda-forge
packaging                        24.2             py313h06a4308_0
pandas                           2.3.2            pypi_0              pypi
pandocfilters                    1.5.0            pyhd8ed1ab_0        conda-forge
pango                            1.50.7           h668f713_2
parso                            0.8.4            pyhd8ed1ab_1        conda-forge
pcre2                            10.42            hebb0a14_1
pexpect                          4.9.0            pyhd8ed1ab_1        conda-forge
pickleshare                      0.7.5            pyhd8ed1ab_1004     conda-forge
pip                              25.1             pyhc872135_2
pixman                           0.40.0           h7f8727e_1
platformdirs                     4.3.7            py313h06a4308_0
playwright                       1.55.0           pypi_0              pypi
pluggy                           1.5.0            py313h06a4308_0
poppler                          24.09.0          h3f9a6df_3
poppler-data                     0.4.11           h06a4308_1
prometheus_client                0.22.1           pyhd8ed1ab_0        conda-forge
prompt-toolkit                   3.0.51           pyha770c72_0        conda-forge
psutil                           5.9.0            py313h5eee18b_1
pthread-stubs                    0.3              h0ce48e5_1
ptyprocess                       0.7.0            pyhd8ed1ab_1        conda-forge
pure_eval                        0.2.3            pyhd8ed1ab_1        conda-forge
pybind11-abi                     5                hd3eb1b0_0
pycosat                          0.6.6            py313h5eee18b_2
pycparser                        2.21             pyhd3eb1b0_0
pydantic                         2.11.7           py313h06a4308_0
pydantic-core                    2.33.2           py313hc6f7160_0
pyee                             13.0.0           pypi_0              pypi
pygments                         2.19.1           py313h06a4308_0
pygraphviz                       1.14             py313h5eee18b_1
pysocks                          1.7.1            py313h06a4308_0
python                           3.13.5           h4612cfd_100_cp313
python-dateutil                  2.9.0.post0      pyhe01879c_2        conda-forge
python-fastjsonschema            2.21.1           pyhd8ed1ab_0        conda-forge
python-json-logger               2.0.7            pyhd8ed1ab_0        conda-forge
python-on-whales                 0.78.0           pypi_0              pypi
python_abi                       3.13             0_cp313
pytz                             2025.2           pyhd8ed1ab_0        conda-forge
pyyaml                           6.0.2            pyhe1237c8_2        conda-forge
pyzmq                            26.2.0           py313h6a678d5_0
readline                         8.2              h5eee18b_0
referencing                      0.36.2           pyh29332c3_0        conda-forge
reproc                           14.2.4           h6a678d5_2
reproc-cpp                       14.2.4           h6a678d5_2
requests                         2.32.4           py313h06a4308_0
rfc3339-validator                0.1.4            pyhd8ed1ab_1        conda-forge
rfc3986-validator                0.1.1            pyh9f0ad1d_0        conda-forge
rfc3987-syntax                   1.1.0            pyhe01879c_1        conda-forge
rich                             13.9.4           py313h06a4308_0
roman-numerals-py                3.1.0            pypi_0              pypi
rpds-py                          0.22.3           py313h4aa5aa6_0
ruamel.yaml                      0.18.10          py313h5eee18b_0
ruamel.yaml.clib                 0.2.12           py313h5eee18b_0
send2trash                       1.8.3            pyh0d859eb_1        conda-forge
setuptools                       72.1.0           py313h06a4308_0
simdjson                         3.10.1           hdb19cb5_0
six                              1.17.0           pyhe01879c_1        conda-forge
sniffio                          1.3.1            pyhd8ed1ab_1        conda-forge
snowballstemmer                  3.0.1            pypi_0              pypi
soupsieve                        2.7              pyhd8ed1ab_0        conda-forge
spdlog                           1.11.0           hdb19cb5_0
sphinx                           8.2.3            pypi_0              pypi
sphinxcontrib-applehelp          2.0.0            pypi_0              pypi
sphinxcontrib-devhelp            2.0.0            pypi_0              pypi
sphinxcontrib-htmlhelp           2.1.0            pypi_0              pypi
sphinxcontrib-jsmath             1.0.1            pypi_0              pypi
sphinxcontrib-qthelp             2.0.0            pypi_0              pypi
sphinxcontrib-serializinghtml    2.0.0            pypi_0              pypi
sqlite                           3.50.2           hb25bd0a_1
stack_data                       0.6.3            pyhd8ed1ab_1        conda-forge
terminado                        0.18.1           pyh0d859eb_0        conda-forge
tinycss2                         1.4.0            pyhd8ed1ab_0        conda-forge
tk                               8.6.14           h993c535_1
tomli                            2.2.1            pyhe01879c_2        conda-forge
tornado                          6.5.1            py313h5eee18b_0
tqdm                             4.67.1           py313h7040dfc_0
traitlets                        5.14.3           pyhd8ed1ab_1        conda-forge
truststore                       0.10.0           py313h06a4308_0
types-python-dateutil            2.9.0.20250708   pyhd8ed1ab_0        conda-forge
typing-extensions                4.12.2           py313h06a4308_0
typing-inspection                0.4.0            py313h06a4308_0
typing_extensions                4.12.2           py313h06a4308_0
typing_utils                     0.1.0            pyhd8ed1ab_1        conda-forge
tzdata                           2025.2           pypi_0              pypi
uri-template                     1.3.0            pyhd8ed1ab_1        conda-forge
urllib3                          2.5.0            py313h06a4308_0
wcwidth                          0.2.13           pyhd8ed1ab_1        conda-forge
webcolors                        24.11.1          pyhd8ed1ab_0        conda-forge
webencodings                     0.5.1            pyhd8ed1ab_3        conda-forge
websocket-client                 1.8.0            pyhd8ed1ab_1        conda-forge
wheel                            0.45.1           py313h06a4308_0
widgetsnbextension               4.0.14           pypi_0              pypi
wrapt                            1.17.3           pypi_0              pypi
xorg-libx11                      1.8.12           h9b100fa_1
xorg-libxau                      1.0.12           h9b100fa_0
xorg-libxcomposite               0.4.6            h9b100fa_2
xorg-libxcursor                  1.2.3            h9b100fa_0
xorg-libxdamage                  1.1.6            h9b100fa_0
xorg-libxdmcp                    1.1.5            h9b100fa_0
xorg-libxext                     1.3.6            h9b100fa_0
xorg-libxfixes                   6.0.1            h9b100fa_0
xorg-libxi                       1.8.2            h9b100fa_0
xorg-libxinerama                 1.1.5            h50385e7_1
xorg-libxrandr                   1.5.4            h9b100fa_0
xorg-libxrender                  0.9.12           h9b100fa_0
xorg-libxtst                     1.2.5            h9b100fa_3
xorg-xorgproto                   2024.1           h5eee18b_1
xz                               5.6.4            h5eee18b_1
yaml                             0.2.5            h7f98852_2          conda-forge
yaml-cpp                         0.8.0            h6a678d5_1
zeromq                           4.3.5            h6a678d5_0
zipp                             3.23.0           pyhd8ed1ab_0        conda-forge
zlib                             1.2.13           h5eee18b_1
zstandard                        0.23.0           py313h2c38b39_1
zstd                             1.5.6            hc292b87_0
```
